<template>
  <div class="about">
    <!-- This file is generated by Vue -->
    <h1>This is an about page</h1>
    <h1>Basically a testing page</h1>

    <VideoPlayer></VideoPlayer>
  </div>
</template>

<script>
import VideoPlayer from "@/components/VideoPlayer.vue";

export default {
  data() {
    return {
      components: {
        VideoPlayer,
      },
    };
  },
  setup() {
    
  },
  methods: {
    
  },
};
</script>
