<template>
  <div class="about">
    <!-- This file is generated by Vue -->
    <h1>This is an about page</h1>
    <h1>Basically a testing page</h1>
    <p>Your token: {{ token }}</p>
    <b-form @submit.prevent="onLogout">
      <b-button type="submit" variant="primary">Logout</b-button>
    </b-form>

    <VideoPlayer></VideoPlayer>
  </div>
</template>

<script>
import router from "@/router";
import axios from "@/axios";
import VideoPlayer from "@/components/VideoPlayer.vue";

export default {
  data() {
    return {
      components: {
        VideoPlayer,
      },
    };
  },
  setup() {
    const token = localStorage.getItem("jwt-token")
    if (token) {
      return { token: token };
    }
    return { token: "No Token (impossible, something is wrong)" };
  },
  methods: {
    // code for logout
    async onLogout() {
      const token = localStorage.getItem("jwt-token");
      const token_refresh = localStorage.getItem("jwt-token-refresh");
      if (token) {
        localStorage.removeItem('jwt-token')
        axios.defaults.headers.common['Authorization'] = '';
      }
      if (token_refresh) {
        localStorage.removeItem("jwt-token-refresh");
      }
      await router.push({ name: "Log-In" });
    },
  },
};
</script>
